"""50 trendin anlamsal secim profilleri (karar 0077).

Bu dosya VERIDIR: urun kimligi/baslik/marka yazilmaz, yalnizca terimler. Urunler
her calistirmada GERCEK katalogdan secilir. Terimler katlanmis (ASCII, kucuk
harf) yazilir; "$" ile biten terim kelimenin tamamini ister (bkz. `text.py`).

Muhafazakar kural: bir trendi besleyecek GUVENILIR sinyal katalogda yoksa
profil `core` bos birakilir (`note` nedenini soyler). Alakasiz urunle doldurmak
yerine trend bos kalir ve arayuzde gorunmez.
"""

from __future__ import annotations

from dataclasses import replace

from curate.selection import Profile

SKIN = ("saglik-kozmetik",)
#: Giyim bazi feed'lerde `spor-outdoor` altinda (production: North Sails, For Fun);
#: moda trendleri her ikisine bakar. Termos/bardak gurultusu `_finalize`da elenir.
MODA = ("moda", "spor-outdoor")
EV = ("ev-yasam",)

#: Kozmetik kategorisine sizan gida/takviye/sac/parfum urunleri: cilt ve makyaj
#: trendlerinin hicbirinde yeri yok.
BEAUTY_NOISE = (
    "sampuan",
    "parfum",
    "edp",
    "edt",
    "unu$",
    "granola",
    "kapsul",
    "tablet",
    "solgar",
    "kolajen tablet",
    "protein",
    "organik nohut",
    "tirnak",
    "dis temizle",
    "dis macun",
    "dis fircasi",
    "sac ",
    "sac$",
    "saclar",
    "deodorant",
    "antiperspirant",
    "roll-on",
    "invisible dry",
    "banyo",
    "bebek",
    "pediatrik",
    "cocuk",
)
#: Bebek/yapi urunleri ev trendlerine sizmasin.
HOME_NOISE = ("bebek", "grohe", "batarya", "lavabo", "dus ", "sabunluk", "musluk", "test")

DRESSY_NOISE = ("sneaker", "sweat", "spor", "bikini", "mayo", "tisort", "sort$")

_P = Profile

PROFILES: tuple[Profile, ...] = (
    # --- Guzellik --------------------------------------------------------
    _P(
        "kuru-ciltlere-son",
        core=(
            "nemlendirici",
            "hyaluron",
            "seramid",
            "ceramide",
            "bariyer",
            "barrier",
            "kuru cilt",
            "hidrasyon",
            "hydrating",
            "hydro",
            "moisturi",
            "nem verici",
        ),
        boost=("krem", "cream", "serum", "ampul", "ampoule", "panthenol", "squalane", "cica"),
        exclude=BEAUTY_NOISE + ("temizle", "cleanser", "kopuk", "foam", "dudak", "maske"),
        categories=SKIN,
    ),
    _P(
        "cam-gibi-bir-cilt",
        core=(
            "hyaluron",
            "glow",
            "glass skin",
            "ampul",
            "ampoule",
            "essence",
            "toner",
            "tonik",
            "snail",
            "aqua",
            "dewy",
        ),
        boost=("serum", "nemlendirici", "cilt", "krem", "cream", "niacinamide"),
        exclude=BEAUTY_NOISE
        + (
            "temizle",
            "cleanser",
            "kopuk",
            "foam",
            "ruj",
            "allik",
            "fondoten",
            "maskara",
            "pudra",
            "tint",
            "fircasi",
            "gunes",
            "bronzer",
            "bb krem",
            "kapatici",
            "vucut",
            "body",
        ),
        categories=SKIN,
    ),
    _P(
        "cildi-isil-isil-yapanlar",
        core=(
            "aydinlat",
            "brighten",
            "bright",
            "vitamin c",
            "c vitamin",
            "glutathione",
            "niacinamide",
            "parlat",
            "isilti",
            "radiance",
            "ton esitle",
            "tone up",
        ),
        boost=("serum", "krem", "cream", "ampul", "ampoule", "maske"),
        exclude=BEAUTY_NOISE
        + (
            "temizle",
            "cleanser",
            "kopuk",
            "foam",
            "ruj",
            "fondoten",
            "maskara",
            "fircasi",
            "dudak",
            "gunes kremi",
            "spf",
            "allik",
            "blusher",
            "intimate",
            "intim",
        ),
        categories=SKIN,
    ),
    _P(
        "sivilceye-karsi-favoriler",
        core=(
            "akne",
            "acne",
            "sivilce",
            "azelaik",
            "azelaic",
            "azela",
            "salisilik",
            "salicylic",
            "bha",
            "cay agaci",
            "tea tree",
            "sebum",
            "keracnyl",
            "yagli ve",
        ),
        boost=("serum", "jel", "gel", "krem", "tonik", "temizle", "cleanser", "kopuk"),
        exclude=tuple(t for t in BEAUTY_NOISE if t != "banyo") + ("ruj", "fondoten", "maskara"),
        categories=SKIN,
    ),
    _P(
        "gozenek-gorunumune-karsi",
        core=("gozenek", "pore", "poreshot", "sebum"),
        boost=("bha", "tonik", "toner", "maske", "serum", "niacinamide", "temizle", "kopuk"),
        exclude=BEAUTY_NOISE + ("ruj", "maskara", "fondoten"),
        categories=SKIN,
    ),
    _P(
        "gunes-lekelerine-karsi",
        core=(
            "leke",
            "dark spot",
            "melazero",
            "pigment",
            "traneksamik",
            "tranexamic",
            "ton esitle",
            "spf",
            "gunes kremi",
            "sunscreen",
            "sun cream",
            "sun stick",
            "sun essence",
            "gunes koruy",
        ),
        boost=("serum", "krem", "cream", "vitamin c", "niacinamide", "aydinlat"),
        exclude=BEAUTY_NOISE
        + ("fondoten", "ruj", "allik", "pudra", "tint", "after sun", "sonrasi", "dudak"),
        categories=SKIN,
    ),
    _P(
        "makyajsiz-guzel-gorun",
        core=(
            "tint",
            "bb krem",
            "cc krem",
            "tone up",
            "tone-up",
            "serum fondoten",
            "skin tint",
            "hafif kapatici",
            "isiltili",
        ),
        boost=("glow", "nemlendirici", "spf", "krem", "allik", "blush", "hafif", "dewy", "natural"),
        exclude=BEAUTY_NOISE
        + (
            "ruj",
            "maskara",
            "eyeliner",
            "oje",
            "maske",
            "temizle",
            "kas ",
            "brow",
            "eyebrow",
            "mask$",
        ),
        categories=SKIN,
        min_score=3.0,
    ),
    _P(
        "5-dakikada-hazir",
        core=(
            "maskara",
            "kas jeli",
            "kas kalemi",
            "brow",
            "ruj",
            "allik",
            "blush",
            "pudra",
            "kapatici",
            "eyeliner",
            "bb krem",
            "fondoten",
            "highlighter",
            "aydinlatici pudra",
        ),
        boost=("mat", "tint", "uzun sureli", "kalici", "hizli"),
        exclude=BEAUTY_NOISE + ("temizle", "makyaj temizle", "peeling", "fircasi"),
        categories=SKIN,
    ),
    _P(
        "cantadan-eksik-olmayanlar",
        core=(
            "lipbalm",
            "lip balm",
            "dudak balm",
            "dudak kremi",
            "dudak nem",
            "el kremi",
            "hand cream",
            "sun stick",
            "gunes stick",
            "sunscreen stick",
            "seyahat boy",
        ),
        boost=("nemlendirici", "spf", "krem", "balm", "tint"),
        exclude=tuple(t for t in BEAUTY_NOISE if t not in ("deodorant", "roll-on"))
        + ("deodorant", "antiperspirant", "roll-on", "sampuan", "parfum", "edp", "edt"),
        categories=SKIN,
    ),
    _P(
        "uygun-fiyatli-guzellik-favorileri",
        core=(
            "krem",
            "serum",
            "ruj",
            "maskara",
            "allik",
            "pudra",
            "fondoten",
            "tonik",
            "toner",
            "maske",
            "temizle",
            "cleanser",
            "gunes",
            "nemlendirici",
            "tint",
            "eyeliner",
        ),
        boost=("nemlendirici", "cilt", "hyaluron", "niacinamide", "mat"),
        exclude=BEAUTY_NOISE + ("sonrasi",),
        categories=SKIN,
        price_max=30000,
        min_score=4.0,
    ),
    _P(
        "pahali-gorunup-ucuz-olanlar",
        note="'Pahali gorunme' ve 'dupe' iliskisi icin katalogda dogrulanabilir sinyal yok "
        "(referans urun cifti/benzerlik kenari yok); bos birakildi.",
    ),
    # --- Moda: sezonluk --------------------------------------------------
    _P(
        "sonbahara-hazir-misin",
        core=(
            "kazak",
            "triko",
            "hirka",
            "mont",
            "kaban",
            "trenc",
            "ceket",
            "bot$",
            "cizme",
            "suet",
            "kadife",
            "kapitone",
            "loafer",
            "oxford",
        ),
        boost=("kalin", "uzun kollu", "yun", "deri", "oversize", "bordo", "haki", "kahve"),
        exclude=(
            "yazlik",
            "sort$",
            "bikini",
            "mayo",
            "plaj",
            "sandalet",
            "terlik",
            "keten",
            "polo",
        ),
        categories=MODA,
    ),
    _P(
        "yagmurlu-gunler-icin",
        core=(
            "yagmurluk",
            "trenc",
            "semsiye",
            "su gecirmez",
            "suya dayanikli",
            "water resistant",
            "waterproof",
            "yagmur",
        ),
        boost=("kapusonlu", "uzun", "mont", "ceket", "bot$"),
        categories=MODA,
    ),
    _P(
        "kazak-mevsimi-basladi",
        core=("kazak", "triko", "hirka", "balikci yaka", "orgu"),
        boost=("oversize", "yun", "bol", "boyun", "fitilli", "kalin"),
        exclude=("sweatshirt", "tisort", "elbise", "canta", "cuzdan"),
        categories=MODA,
    ),
    _P(
        "havalar-sogurken",
        core=(
            "mont",
            "kaban",
            "sisme",
            "kapitone",
            "parka",
            "polar",
            "yun$",
            "shearling",
            "kurk",
            "pelus",
            "bere",
            "atki",
            "eldiven",
            "termal",
        ),
        boost=("kalin", "kapusonlu", "astarli", "kazak", "triko"),
        exclude=("yazlik", "sort$", "bikini", "mayo", "plaj", "keten", "sandalet", "terlik"),
        categories=MODA,
    ),
    _P(
        "kis-gelmeden-al",
        core=(
            "mont",
            "kaban",
            "parka",
            "bere",
            "atki",
            "eldiven",
            "kurk",
            "pelus",
            "kapitone",
            "bot$",
            "cizme",
            "sisme",
        ),
        boost=("kalin", "astarli", "kapusonlu", "deri", "kalin tabanli"),
        exclude=(
            "yazlik",
            "sort$",
            "bikini",
            "mayo",
            "plaj",
            "keten",
            "sandalet",
            "terlik",
            "polo",
        ),
        categories=MODA,
    ),
    _P(
        "bu-sonbaharin-renkleri",
        core=(
            "bordo",
            "burgundy",
            "merlot",
            "marsala",
            "bordeaux",
            "haki",
            "camel",
            "kahverengi",
            "kahve$",
            "taba$",
            "hardal",
            "zeytin yesil",
            "terracotta",
            "kiremit",
            "vizon",
        ),
        boost=("kazak", "triko", "ceket", "mont", "canta", "bot$", "pantolon", "etek", "elbise"),
        categories=MODA,
    ),
    _P(
        "kahve-tonlari",
        core=("kahverengi", "kahve$", "camel", "taba$", "vizon", "cikolata", "mocha", "kum rengi"),
        boost=("deri", "suet", "kazak", "triko", "canta", "bot$", "pantolon", "ceket"),
        categories=MODA,
    ),
    _P(
        "bordo-geri-dondu",
        core=("bordo", "burgundy", "merlot", "marsala", "bordeaux", "visne"),
        boost=("canta", "bot$", "ceket", "kazak", "triko", "pantolon", "elbise", "etek", "suet"),
        categories=MODA,
    ),
    # --- Moda: temel parcalar -------------------------------------------
    _P(
        "kot-her-yerde",
        core=("kot$", "denim", "jean$", "jeans"),
        boost=("pantolon", "ceket", "etek", "gomlek", "yuksek bel", "straight"),
        exclude=("canta", "cuzdan"),
        categories=MODA,
    ),
    _P(
        "babetler-geri-dondu",
        core=("babet", "balerin", "ballet flat"),
        categories=MODA,
    ),
    _P(
        "bol-paca-sezonu",
        core=("bol paca", "genis paca", "wide leg", "palazzo", "parasut", "bol kesim", "paca bol"),
        boost=("pantolon", "kot", "yuksek bel", "kumas"),
        categories=MODA,
    ),
    _P(
        "bir-dolap-onlarca-kombin",
        core=("basic", "duz renk", "bodysuit", "straight"),
        boost=("tisort", "pantolon", "gomlek", "kazak", "triko", "pamuk", "bisiklet yaka"),
        exclude=("bikini", "mayo", "plaj"),
        categories=MODA,
        min_score=4.0,
    ),
    _P(
        "az-parcayla-cok-kombin",
        core=(
            "blazer",
            "trenc",
            "gomlek",
            "kumas pantolon",
            "klasik pantolon",
            "yuksek bel",
            "triko",
            "bodysuit",
        ),
        boost=("siyah", "bej", "krem", "beyaz", "lacivert", "gri", "basic"),
        exclude=("bikini", "mayo", "plaj", "sweatshirt"),
        categories=MODA,
        min_score=5.0,
    ),
    _P(
        "her-gun-giyilecekler",
        core=("tisort", "sweatshirt", "basic", "bisiklet yaka", "sneaker", "kot$"),
        boost=("pamuk", "rahat", "regular fit", "esnek", "oversize"),
        exclude=("bikini", "mayo", "plaj", "abiye"),
        categories=MODA,
        min_score=5.0,
    ),
    _P(
        "dolabin-kurtaricilari",
        core=("trenc", "blazer", "kot ceket", "loafer", "gomlek"),
        boost=("siyah", "bej", "lacivert", "klasik", "deri", "krem"),
        exclude=("bikini", "mayo", "plaj"),
        categories=MODA,
        min_score=5.0,
    ),
    _P(
        "kampus-kombinleri",
        core=(
            "sweatshirt",
            "hoodie",
            "kapusonlu",
            "sneaker",
            "spor ayakkabi",
            "kot$",
            "jean$",
            "tisort",
            "sirt cantasi",
            "cargo",
            "oversize",
        ),
        boost=("basic", "pamuk", "rahat", "regular fit", "unisex"),
        exclude=("bikini", "mayo", "plaj", "abiye", "topuklu"),
        categories=MODA,
        min_score=4.0,
    ),
    # --- Moda: is ve davet ------------------------------------------------
    _P(
        "ise-donus-kombinleri",
        core=(
            "gomlek",
            "blazer",
            "kumas pantolon",
            "klasik",
            "kalem etek",
            "loafer",
            "oxford",
            "topuklu",
            "pump",
            "omuz cantasi",
        ),
        boost=("siyah", "lacivert", "deri", "krem", "bej"),
        exclude=DRESSY_NOISE,
        categories=MODA,
        min_score=4.0,
    ),
    _P(
        "ofisten-aksam-yemegine",
        core=("elbise", "topuklu", "pump", "saten", "blazer", "clutch", "abiye", "omuz cantasi"),
        boost=("siyah", "midi", "saten", "deri", "kare"),
        exclude=DRESSY_NOISE,
        categories=MODA,
        min_score=4.0,
    ),
    _P(
        "dugun-sezonu",
        core=("abiye", "saten", "topuklu", "pump", "clutch", "davet", "payet", "tul"),
        boost=("elbise", "ince topuklu", "midi", "uzun"),
        exclude=DRESSY_NOISE,
        categories=MODA,
    ),
    _P(
        "nisan-ve-davet-elbiseleri",
        core=(
            "abiye",
            "davet",
            "nisan",
            "saten elbise",
            "payet",
            "tul elbise",
            "midi elbise",
            "maxi elbise",
            "uzun elbise",
            "kokteyl",
        ),
        boost=("elbise", "saten", "drape", "yirtmac"),
        exclude=DRESSY_NOISE + ("tisort elbise", "sweat"),
        categories=MODA,
    ),
    _P(
        "mezuniyet-icin-ne-giyilir",
        core=("mezuniyet", "abiye", "saten", "pump", "midi elbise", "kokteyl"),
        boost=("elbise", "mini elbise", "topuklu", "siyah", "krem"),
        exclude=DRESSY_NOISE,
        categories=MODA,
    ),
    _P(
        "bayramlik-bakmaya-baslayanlara",
        core=(
            "abiye",
            "saten",
            "midi elbise",
            "uzun elbise",
            "takim",
            "klasik ayakkabi",
            "loafer",
            "oxford",
            "topuklu",
            "pump",
            "klasik gomlek",
        ),
        boost=("siyah", "lacivert", "krem", "deri"),
        exclude=DRESSY_NOISE,
        categories=MODA,
    ),
    # --- Moda: tatil ----------------------------------------------------
    _P(
        "tatile-cikmadan-once",
        core=(
            "sort$",
            "mayo",
            "bikini",
            "keten",
            "sapka$",
            "plaj",
            "sandalet",
            "terlik",
            "polo",
            "uv korumali",
            "valiz",
            "bavul",
            "seyahat",
        ),
        boost=("hafif", "pamuk", "esnek", "yazlik"),
        categories=MODA,
        min_score=3.0,
    ),
    _P(
        "ege-yazi",
        core=(
            "keten",
            "sort$",
            "yazlik",
            "hasir",
            "sandalet",
            "terlik",
            "mayo",
            "bikini",
            "sapka$",
            "pamuk elbise",
        ),
        boost=("hafif", "pamuk", "bol", "rahat"),
        categories=MODA,
    ),
    _P(
        "sahile-giderken",
        core=(
            "mayo",
            "bikini",
            "plaj",
            "pareo",
            "sapka$",
            "sort$",
            "terlik",
            "sandalet",
            "deniz sort",
            "uv korumali",
        ),
        boost=("hafif", "hizli kuruyan", "keten", "pamuk"),
        categories=MODA + ("ev-yasam",),
        exclude=HOME_NOISE,
    ),
    _P(
        "hafta-sonu-kacamagi",
        core=(
            "seyahat",
            "sirt cantasi",
            "duffel",
            "bel cantasi",
            "crossbody",
            "capraz canta",
            "hasir canta",
        ),
        boost=("hafif", "kucuk", "mini", "rahat"),
        categories=MODA,
        min_score=3.0,
    ),
    # --- Ogrenci ----------------------------------------------------------
    _P(
        "okula-donus-listesi",
        core=(
            "sirt cantasi",
            "backpack",
            "laptop case",
            "laptop kilif",
            "laptop canta",
            "matara",
            "termos",
            "okul",
        ),
        boost=("hafif", "su gecirmez", "kapasite", "kilifi"),
        exclude=("bebek", "yemek termosu", "test"),
        categories=MODA + ("elektronik",),
    ),
    _P(
        "universiteye-baslayanlar-icin",
        core=(
            "sirt cantasi",
            "backpack",
            "laptop case",
            "laptop kilif",
            "laptop canta",
            "termos",
            "mug$",
        ),
        boost=("sweatshirt", "sneaker", "hafif", "unisex"),
        exclude=("bebek", "yemek termosu", "test"),
        categories=MODA + ("elektronik",),
    ),
    _P(
        "kyk-odasinin-olmazsa-olmazlari",
        core=(
            "organizer",
            "nevresim",
            "yorgan",
            "pike",
            "battaniye",
            "masa lambasi",
            "carsaf",
            "havlu",
            "calisma masasi",
        ),
        boost=("pamuk", "tekli", "tek kisilik", "masa", "duzenleyici"),
        exclude=HOME_NOISE + ("havuz", "plaj", "hali", "komodin", "sarkit", "lambader", "divan"),
        categories=EV,
        # Yurt odasi butcesi: pahali mobilya (komodin, calisma masasi) bu trendin konusu degil.
        price_max=500_000,
    ),
    _P(
        "ogrenci-evi-kurtaricilari",
        core=(
            "organizer",
            "cop kovas",
            "cop kutusu",
            "battaniye",
            "nevresim",
            "havlu",
            "paspas",
            "askilik",
            "temizlik",
        ),
        boost=("pratik", "katlanir", "pamuk", "kompakt"),
        exclude=HOME_NOISE,
        categories=EV,
        price_max=500_000,
        min_score=3.0,
    ),
    _P(
        "evi-daha-pahali-gosteren-seyler",
        core=(
            "kadife",
            "keten",
            "el dokuma",
            "jut",
            "sisal",
            "kilim",
            "hali",
            "ahsap",
            "boucle",
            "fitilli",
        ),
        boost=("dogal", "doku", "minder", "yastik", "kilifi", "yun"),
        exclude=HOME_NOISE,
        categories=EV,
        # Uc fiyat (300.000 TL halı) 'temel ev' / 'uygun görünen' fikrine aykırı: tavan 10.000 TL.
        price_max=1_000_000,
    ),
    _P(
        "kucuk-eve-buyuk-fikirler",
        core=(
            "organizer",
            "katlan",
            "istifle",
            "raf$",
            "kompakt",
            "portmanto",
            "askilik",
        ),
        boost=("tekli", "modul", "pratik", "yer tasarruf"),
        exclude=HOME_NOISE,
        categories=EV,
        min_score=3.0,
    ),
    _P(
        "yeni-eve-cikanlar-icin",
        core=(
            "hali",
            "nevresim",
            "havlu",
            "cop kovas",
            "cop kutusu",
            "battaniye",
            "yastik",
            "perde",
            "lamba",
            "organizer",
            "paspas",
        ),
        boost=("takim", "pamuk", "set", "pratik"),
        exclude=HOME_NOISE,
        categories=EV,
        # Uc fiyat (300.000 TL halı) 'temel ev' / 'uygun görünen' fikrine aykırı: tavan 10.000 TL.
        price_max=1_000_000,
        min_score=3.0,
    ),
    _P(
        "kahve-kosesi-kuruyoruz",
        core=(
            "kahve makinesi",
            "french press",
            "moka",
            "espresso makine",
            "cezve",
            "filtre kahve",
            "kahve fincan",
            "kupa$",
            "fincan",
            "sut kopurtuc",
            "kahve degirmen",
            "cold brew",
            "v60",
            "chemex",
            "aeropress",
        ),
        boost=("seramik", "porselen", "paslanmaz", "cam"),
        exclude=HOME_NOISE
        + (
            "termos",
            "tumbler",
            "transit",
            "fliptop",
            "quencher",
            "mug$",
            "yemek termosu",
            "cold mug",
        ),
    ),
    _P(
        "masa-basinda-daha-keyifli",
        core=(
            "klavye",
            "mouse$",
            "mouse pad",
            "mousepad",
            "masa lambasi",
            "laptop stand",
            "monitor stand",
            "calisma sandalye",
            "ofis sandalye",
        ),
        boost=("kablosuz", "wireless", "mekanik", "ergonomik", "rgb"),
        exclude=(
            "tus takimi",
            "keycap",
            "stabilizer",
            "switch",
            "skates",
            "lube",
            "kablo$",
            "pcb",
            "plate",
            "foam",
            "kilifi",
            "case$",
            "kit$",
            "tool",
            "puller",
            "tus",
            "kapak",
            "ayak",
            "grip",
            "skate",
            "bungee",
        ),
        categories=("elektronik", "ev-yasam"),
    ),
    _P(
        "evde-sonbahar-havasi",
        core=("battaniye", "kadife", "yun", "pike", "mum", "kilim", "hali", "minder", "yastik"),
        boost=(
            "bordo",
            "kahve",
            "hardal",
            "camel",
            "terracotta",
            "kiremit",
            "haki",
            "zeytin",
            "turuncu",
            "bej",
            "kahverengi",
        ),
        exclude=HOME_NOISE,
        categories=EV,
        # Uc fiyat (300.000 TL halı) 'temel ev' / 'uygun görünen' fikrine aykırı: tavan 10.000 TL.
        price_max=1_000_000,
        min_boost=1,
    ),
    # --- Kampanya / ortak: guvenilir sinyal yok -----------------------------
    _P(
        "11-11de-alinacaklar",
        note="Kampanya katilimi/indirim verisi katalogda yok; kampanya urunu uydurulmaz.",
    ),
    _P(
        "kasim-indirimlerinde-beklenenler",
        note="Gecmis kasim fiyat verisi/indirim sinyali yok; bos birakildi.",
    ),
    _P(
        "herkes-almadan-once",
        note="Populerlik/talep sinyali (tiklama, favori) yok; bu iddia dogrulanamaz.",
    ),
)

#: Her profilde gecerli: on siparis urunu "su an stokta" degildir; test kayitlari.
GLOBAL_EXCLUDE = ("on siparis", "test")
#: `spor-outdoor` altindaki termos/bardak, renk adlariyla (haki, camel) moda trendlerine girmesin.
DRINKWARE_NOISE = ("termos", "mug$", "bardak", "tumbler", "quencher", "bottle", "matara")
#: Cocuk urunu bu trendlerde anlamli (okul esyasi); digerlerinde yetiskin odagi.
_KIDS_OK = frozenset({"okula-donus-listesi", "universiteye-baslayanlar-icin"})


def _finalize(profile: Profile) -> Profile:
    extra = GLOBAL_EXCLUDE
    if "moda" in profile.categories and profile.slug not in _KIDS_OK:
        extra = extra + ("cocuk",) + DRINKWARE_NOISE
    return replace(profile, exclude=tuple(dict.fromkeys(profile.exclude + extra)))


PROFILES = tuple(_finalize(p) for p in PROFILES)
BY_SLUG: dict[str, Profile] = {p.slug: p for p in PROFILES}
